import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Koodu</a>
        </h1>

        <p className={styles.description}>
          Koodu is a suite of Suite of open-source tools for DevX teams 
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/koodu-app/scrawl" className={styles.card}>
            <h2>Scrawl &rarr;</h2>
            <p> Single page app to write step by step tutorials powered by netlify CMS, inspired by google codelabs</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Merge Engine &rarr;</h2>
            <p>Node script to dynamically merge refernce and non-reference content for OpenAPI 2.0 specs </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Doc gen &rarr;</h2>
            <p>Genreate interactive api docs for openapi 2.0 specs</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2> Analytics &rarr;</h2>
            <p>
            Analytics for devex teams
            </p>
          </a>
        </div>
      </main>

    </div>
  )
}
